
// Vietnamese provinces and cities
export const provinces = [
  { code: '01', name: 'Hà Nội' },
  { code: '79', name: 'TP. Hồ Chí Minh' },
  { code: '48', name: 'Đà Nẵng' },
  { code: '92', name: 'Cần Thơ' },
  { code: '31', name: 'Hải Phòng' },
  { code: '02', name: 'Hà Giang' },
  { code: '04', name: 'Cao Bằng' },
  { code: '06', name: 'Bắc Kạn' },
  { code: '08', name: 'Tuyên Quang' },
  { code: '10', name: 'Lào Cai' },
  { code: '11', name: 'Điện Biên' },
  { code: '12', name: 'Lai Châu' },
  { code: '14', name: 'Sơn La' },
  { code: '15', name: 'Yên Bái' },
  { code: '17', name: 'Hoà Bình' },
  { code: '19', name: 'Thái Nguyên' },
  { code: '20', name: 'Lạng Sơn' },
  { code: '22', name: 'Quảng Ninh' },
  { code: '24', name: 'Bắc Giang' },
  { code: '25', name: 'Phú Thọ' },
  { code: '26', name: 'Vĩnh Phúc' },
  { code: '27', name: 'Bắc Ninh' },
  { code: '30', name: 'Hải Dương' },
  { code: '33', name: 'Hưng Yên' },
  { code: '34', name: 'Thái Bình' },
  { code: '35', name: 'Hà Nam' },
  { code: '36', name: 'Nam Định' },
  { code: '37', name: 'Ninh Bình' },
  { code: '38', name: 'Thanh Hóa' },
  { code: '40', name: 'Nghệ An' },
  { code: '42', name: 'Hà Tĩnh' },
  { code: '44', name: 'Quảng Bình' },
  { code: '45', name: 'Quảng Trị' },
  { code: '46', name: 'Thừa Thiên Huế' },
  { code: '49', name: 'Quảng Nam' },
  { code: '51', name: 'Quảng Ngãi' },
  { code: '52', name: 'Bình Định' },
  { code: '54', name: 'Phú Yên' },
  { code: '56', name: 'Khánh Hòa' },
  { code: '58', name: 'Ninh Thuận' },
  { code: '60', name: 'Bình Thuận' },
  { code: '62', name: 'Kon Tum' },
  { code: '64', name: 'Gia Lai' },
  { code: '66', name: 'Đắk Lắk' },
  { code: '67', name: 'Đắk Nông' },
  { code: '68', name: 'Lâm Đồng' },
  { code: '70', name: 'Bình Phước' },
  { code: '72', name: 'Tây Ninh' },
  { code: '74', name: 'Bình Dương' },
  { code: '75', name: 'Đồng Nai' },
  { code: '77', name: 'Bà Rịa - Vũng Tàu' },
  { code: '80', name: 'Long An' },
  { code: '82', name: 'Tiền Giang' },
  { code: '83', name: 'Bến Tre' },
  { code: '84', name: 'Trà Vinh' },
  { code: '86', name: 'Vĩnh Long' },
  { code: '87', name: 'Đồng Tháp' },
  { code: '89', name: 'An Giang' },
  { code: '91', name: 'Kiên Giang' },
  { code: '93', name: 'Hậu Giang' },
  { code: '94', name: 'Sóc Trăng' },
  { code: '95', name: 'Bạc Liêu' },
  { code: '96', name: 'Cà Mau' },
];

// Sample districts for major cities
export const districts: { [key: string]: { code: string; name: string }[] } = {
  '79': [ // TP. HCM
    { code: '760', name: 'Quận 1' },
    { code: '761', name: 'Quận 2' },
    { code: '762', name: 'Quận 3' },
    { code: '763', name: 'Quận 4' },
    { code: '764', name: 'Quận 5' },
    { code: '765', name: 'Quận 6' },
    { code: '766', name: 'Quận 7' },
    { code: '767', name: 'Quận 8' },
    { code: '768', name: 'Quận 9' },
    { code: '769', name: 'Quận 10' },
    { code: '770', name: 'Quận 11' },
    { code: '771', name: 'Quận 12' },
    { code: '772', name: 'Quận Thủ Đức' },
    { code: '773', name: 'Quận Gò Vấp' },
    { code: '774', name: 'Quận Bình Thạnh' },
    { code: '775', name: 'Quận Tân Bình' },
    { code: '776', name: 'Quận Tân Phú' },
    { code: '777', name: 'Quận Phú Nhuận' },
    { code: '783', name: 'Quận Bình Tân' },
    { code: '784', name: 'Huyện Củ Chi' },
    { code: '785', name: 'Huyện Hóc Môn' },
    { code: '786', name: 'Huyện Bình Chánh' },
    { code: '787', name: 'Huyện Nhà Bè' },
    { code: '788', name: 'Huyện Cần Giờ' },
  ],
  '01': [ // Hà Nội
    { code: '001', name: 'Quận Ba Đình' },
    { code: '002', name: 'Quận Hoàn Kiếm' },
    { code: '003', name: 'Quận Tây Hồ' },
    { code: '004', name: 'Quận Long Biên' },
    { code: '005', name: 'Quận Cầu Giấy' },
    { code: '006', name: 'Quận Đống Đa' },
    { code: '007', name: 'Quận Hai Bà Trưng' },
    { code: '008', name: 'Quận Hoàng Mai' },
    { code: '009', name: 'Quận Thanh Xuân' },
    { code: '016', name: 'Huyện Sóc Sơn' },
    { code: '017', name: 'Huyện Đông Anh' },
    { code: '018', name: 'Huyện Gia Lâm' },
    { code: '019', name: 'Quận Nam Từ Liêm' },
    { code: '020', name: 'Huyện Thanh Trì' },
    { code: '021', name: 'Quận Bắc Từ Liêm' },
    { code: '250', name: 'Huyện Mê Linh' },
    { code: '268', name: 'Quận Hà Đông' },
    { code: '269', name: 'Thị xã Sơn Tây' },
    { code: '271', name: 'Huyện Ba Vì' },
    { code: '272', name: 'Huyện Phúc Thọ' },
    { code: '273', name: 'Huyện Đan Phượng' },
    { code: '274', name: 'Huyện Hoài Đức' },
    { code: '275', name: 'Huyện Quốc Oai' },
    { code: '276', name: 'Huyện Thạch Thất' },
    { code: '277', name: 'Huyện Chương Mỹ' },
    { code: '278', name: 'Huyện Thanh Oai' },
    { code: '279', name: 'Huyện Thường Tín' },
    { code: '280', name: 'Huyện Phú Xuyên' },
    { code: '281', name: 'Huyện Ứng Hòa' },
    { code: '282', name: 'Huyện Mỹ Đức' },
  ],
  '48': [ // Đà Nẵng
    { code: '490', name: 'Quận Liên Chiểu' },
    { code: '491', name: 'Quận Thanh Khê' },
    { code: '492', name: 'Quận Hải Châu' },
    { code: '493', name: 'Quận Sơn Trà' },
    { code: '494', name: 'Quận Ngũ Hành Sơn' },
    { code: '495', name: 'Quận Cẩm Lệ' },
    { code: '497', name: 'Huyện Hòa Vang' },
    { code: '498', name: 'Huyện Hoàng Sa' },
  ],
};

// Sample communes/wards
export const communes: { [key: string]: { code: string; name: string }[] } = {
  '760': [ // Quận 1
    { code: '26734', name: 'Phường Tân Định' },
    { code: '26737', name: 'Phường Đa Kao' },
    { code: '26740', name: 'Phường Bến Nghé' },
    { code: '26743', name: 'Phường Bến Thành' },
    { code: '26746', name: 'Phường Nguyễn Thái Bình' },
    { code: '26749', name: 'Phường Phạm Ngũ Lão' },
    { code: '26752', name: 'Phường Cầu Ông Lãnh' },
    { code: '26755', name: 'Phường Cô Giang' },
    { code: '26758', name: 'Phường Nguyễn Cư Trinh' },
    { code: '26761', name: 'Phường Cầu Kho' },
  ],
  '784': [ // Huyện Củ Chi
    { code: '27550', name: 'Thị trấn Củ Chi' },
    { code: '27553', name: 'Xã Phú Mỹ Hưng' },
    { code: '27556', name: 'Xã An Phú' },
    { code: '27559', name: 'Xã Trung Lập Thượng' },
    { code: '27562', name: 'Xã An Nhơn Tây' },
    { code: '27565', name: 'Xã Nhuận Đức' },
    { code: '27568', name: 'Xã Phạm Văn Cội' },
    { code: '27571', name: 'Xã Phú Hòa Đông' },
    { code: '27574', name: 'Xã Trung Lập Hạ' },
    { code: '27577', name: 'Xã Trung An' },
    { code: '27580', name: 'Xã Phước Thạnh' },
    { code: '27583', name: 'Xã Phước Hiệp' },
    { code: '27586', name: 'Xã Tân An Hội' },
    { code: '27589', name: 'Xã Phước Vĩnh An' },
    { code: '27592', name: 'Xã Thái Mỹ' },
    { code: '27595', name: 'Xã Tân Thạnh Tây' },
    { code: '27598', name: 'Xã Hòa Phú' },
    { code: '27601', name: 'Xã Tân Thạnh Đông' },
    { code: '27604', name: 'Xã Bình Mỹ' },
    { code: '27607', name: 'Xã Tân Phú Trung' },
    { code: '27610', name: 'Xã Tân Thông Hội' },
  ],
};

// Sample hamlets for communes
export const hamlets: { [key: string]: string[] } = {
  '27607': [ // Xã Tân Phú Trung
    'Ấp 1',
    'Ấp 2',
    'Ấp 3',
    'Ấp 4',
    'Ấp 5',
    'Ấp 6',
  ],
  '26734': [ // Phường Tân Định
    'Khu phố 1',
    'Khu phố 2',
    'Khu phố 3',
    'Khu phố 4',
  ],
};

// Insurance companies in Vietnam
export const insuranceCompanies = [
  'Prudential Việt Nam',
  'Manulife Việt Nam',
  'AIA Việt Nam',
  'Dai-ichi Life Việt Nam',
  'Sun Life Việt Nam',
  'MB Ageas Life',
  'Generali Việt Nam',
  'FWD Việt Nam',
  'Bảo Việt Nhân Thọ',
  'Bảo Minh',
  'PVI',
  'PTI',
  'PJICO',
  'VietinBank Aviva',
  'Cathay Life Việt Nam',
  'Hanwha Life Việt Nam',
  'Shinhan Life Việt Nam',
  'ACE Life',
  'Prevoir Việt Nam',
  'Fubon Life Việt Nam',
];
